/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Hospede;
import fatec.poo.model.Pessoa;
import fatec.poo.model.QuartoHotel;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author ferna
 */
public class GuiAvaliacao2 extends javax.swing.JFrame {

    /**
     * Creates new form GuiAvaliacaao2
     */
    public GuiAvaliacao2(ArrayList<Pessoa> c, ArrayList<QuartoHotel> h) {
        initComponents();
        cadastro = c;
        hotel = h;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQtdQuartosOcupados = new javax.swing.JTextField();
        txtTotalFat = new javax.swing.JTextField();
        txtQtdQuartosMasc = new javax.swing.JTextField();
        txtQtdeQuartosFem = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("2a. Avaliação de POO - Noite");

        jLabel1.setText("Qtde. de Quartos Ocupados ");

        jLabel2.setText("Total Faturamento Hotel");

        jLabel3.setText("Qtde. de Quartos Ocupados por Hóspedes do Sexo Masculino ");

        jLabel4.setText("Qtde. de Quartos Ocupados por Hóspedes do Sexo Femino");

        txtQtdQuartosOcupados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtQtdQuartosOcupados.setEnabled(false);

        txtTotalFat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTotalFat.setEnabled(false);

        txtQtdQuartosMasc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtQtdQuartosMasc.setEnabled(false);

        txtQtdeQuartosFem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtQtdeQuartosFem.setEnabled(false);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalFat, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(txtQtdQuartosOcupados))))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtQtdQuartosMasc, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txtQtdeQuartosFem))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair)
                .addGap(28, 28, 28))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPesquisar, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtQtdQuartosOcupados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotalFat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQtdQuartosMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQtdeQuartosFem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnSair))
                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtQtdQuartosMasc, txtQtdQuartosOcupados, txtQtdeQuartosFem, txtTotalFat});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        int x;
        int m=0;
        int f=0;
        int q=0;
        double totalHotel=0;
        
        for (x = 0; x < hotel.size(); x++) {
            if (hotel.get(x) instanceof QuartoHotel){
                if(hotel.get(x).isSituacao() == true)
                 q++;
            } 
        }
        
        txtQtdQuartosOcupados.setText(Integer.toString(q));
        
        for (x = 0; x < hotel.size(); x++) {
            if (hotel.get(x) instanceof QuartoHotel){
                totalHotel += hotel.get(x).getTotalFaturado();
            }
        } 
        
        txtTotalFat.setText(df.format(totalHotel));
        
        
        for (x = 0; x < hotel.size(); x++) {
            if (hotel.get(x) instanceof QuartoHotel) {
                if (hotel.get(x).isSituacao()==true && hotel.get(x).getHospede().getSexo().equals("M")){
                    m++;
                }
                else if (hotel.get(x).isSituacao()==true && hotel.get(x).getHospede().getSexo().equals("F")){
                    f++;
                }
            }
        }
        
        txtQtdQuartosMasc.setText(Integer.toString(m));
        txtQtdeQuartosFem.setText(Integer.toString(f));   
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtQtdQuartosMasc;
    private javax.swing.JTextField txtQtdQuartosOcupados;
    private javax.swing.JTextField txtQtdeQuartosFem;
    private javax.swing.JTextField txtTotalFat;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pessoa> cadastro = new ArrayList<Pessoa>();
    private ArrayList<QuartoHotel> hotel = new ArrayList<QuartoHotel>();
    private int posHospede;
    private int posAtendente;
    private int posQuarto;
    DecimalFormat df = new DecimalFormat("#,##0.00");
}
