/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Atendente;
import fatec.poo.model.Hospede;
import fatec.poo.model.Pessoa;
import fatec.poo.model.QuartoHotel;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author ferna
 */
public class GuiReservarLiberar extends javax.swing.JFrame {

    /**
     * Creates new form GuiReservarLiberar
     */
    public GuiReservarLiberar(ArrayList<Pessoa> c, ArrayList<QuartoHotel> h) {
        initComponents();
        cadastro = c;
        hotel = h;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRegFunc = new javax.swing.JTextField();
        txtCpfHospede = new javax.swing.JTextField();
        txtNumQuarto = new javax.swing.JTextField();
        txtDataEntrada = new javax.swing.JTextField();
        txtDataSaida = new javax.swing.JTextField();
        txtTotalPagar = new javax.swing.JTextField();
        txtSituacao = new javax.swing.JTextField();
        txtResultPesqFunc = new javax.swing.JTextField();
        txtResultPesqHospede = new javax.swing.JTextField();
        btnPesqRegFunc = new javax.swing.JButton();
        btnPesqCpfHospede = new javax.swing.JButton();
        btnReservar = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnPesqQuarto = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        jTextField10.setText("jTextField10");

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reg. Func.");

        jLabel2.setText("CPF Hóspede");

        jLabel3.setText("No. Quarto");

        jLabel4.setText("Data de Entrada");

        jLabel5.setText("Data de Saída");

        jLabel6.setText("Valor a Pagar");

        jLabel7.setText("Situação");

        txtRegFunc.setToolTipText("");

        txtCpfHospede.setToolTipText("");
        txtCpfHospede.setEnabled(false);

        txtNumQuarto.setToolTipText("");
        txtNumQuarto.setEnabled(false);

        txtDataEntrada.setToolTipText("");
        txtDataEntrada.setEnabled(false);

        txtDataSaida.setToolTipText("");
        txtDataSaida.setEnabled(false);

        txtTotalPagar.setToolTipText("");
        txtTotalPagar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTotalPagar.setEnabled(false);

        txtSituacao.setToolTipText("");
        txtSituacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtSituacao.setEnabled(false);

        txtResultPesqFunc.setToolTipText("");
        txtResultPesqFunc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtResultPesqFunc.setEnabled(false);

        txtResultPesqHospede.setToolTipText("");
        txtResultPesqHospede.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtResultPesqHospede.setEnabled(false);

        btnPesqRegFunc.setText(". . .");
        btnPesqRegFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqRegFuncActionPerformed(evt);
            }
        });

        btnPesqCpfHospede.setText(". . .");
        btnPesqCpfHospede.setEnabled(false);
        btnPesqCpfHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqCpfHospedeActionPerformed(evt);
            }
        });

        btnReservar.setText("Reservar");
        btnReservar.setEnabled(false);
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnLiberar.setText("Liberar");
        btnLiberar.setEnabled(false);
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnPesqQuarto.setText(". . . ");
        btnPesqQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqQuartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnReservar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesqQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 58, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLiberar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSair))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRegFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txtCpfHospede)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDataSaida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(txtDataEntrada, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesqRegFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesqCpfHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtResultPesqFunc)
                            .addComponent(txtResultPesqHospede))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLiberar, btnReservar, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRegFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResultPesqFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesqRegFunc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCpfHospede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesqCpfHospede)
                    .addComponent(txtResultPesqHospede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesqQuarto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTotalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar)
                    .addComponent(btnLiberar)
                    .addComponent(btnSair))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtResultPesqFunc, txtResultPesqHospede});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesqRegFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqRegFuncActionPerformed
        int x;
        for (x = 0; x < cadastro.size(); x++) {
            if (cadastro.get(x) instanceof Atendente) {
                if (((Atendente) cadastro.get(x)).getRegFunc().equals(txtRegFunc.getText())) {
                    break;
                }
            }
        }
        if (x < cadastro.size()) {
            posAtendente = x;
        } else {
            posAtendente = -1;
        }

        if (posAtendente >= 0) {
            txtResultPesqFunc.setText(null);
            txtCpfHospede.setText(null);
            txtResultPesqHospede.setText(null);
            txtNumQuarto.setText(null);
            txtSituacao.setText(null);
            txtDataEntrada.setText(null);
            txtDataSaida.setText(null);
            txtTotalPagar.setText(null);
            txtResultPesqFunc.setText(cadastro.get(posAtendente).getNome());
            txtRegFunc.setEnabled(false);
            btnPesqRegFunc.setEnabled(false);
            btnPesqCpfHospede.setEnabled(true);
            txtCpfHospede.setEnabled(true);
            txtCpfHospede.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Atendente não cadastrado, favor realizar o cadastro do funcionário ou pesquisar outro");
        }
    }//GEN-LAST:event_btnPesqRegFuncActionPerformed

    private void btnPesqCpfHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqCpfHospedeActionPerformed
        int x;
        for (x = 0; x < cadastro.size(); x++) {
            if (cadastro.get(x) instanceof Hospede) {
                if (((Hospede) cadastro.get(x)).getCpf().equals(txtCpfHospede.getText())) {
                    break;
                }
            }
        }
        if (x < cadastro.size()) {
            posHospede = x;
        } else {
            posHospede = -1;
        }

        if (posHospede >= 0) {
            txtResultPesqHospede.setText(cadastro.get(posHospede).getNome());
            txtCpfHospede.setEnabled(false);
            btnPesqCpfHospede.setEnabled(false);
            if (((Hospede) cadastro.get(posHospede)).getQuartoHotel() != null) {
                txtNumQuarto.setText(Integer.toString(((Hospede) cadastro.get(posHospede)).getQuartoHotel().getNumQuarto()));
                if (((Hospede) cadastro.get(posHospede)).getQuartoHotel().isSituacao() == true) {
                    txtSituacao.setText(" Reservado");
                } else {
                    txtSituacao.setText(" Livre");
                }
                txtDataEntrada.setText((((Hospede) cadastro.get(posHospede)).getQuartoHotel().getDataEntrada()));
                txtDataSaida.setEnabled(true);
                btnReservar.setEnabled(false);
                btnLiberar.setEnabled(true);
                txtDataSaida.requestFocus();
            } else {
                txtCpfHospede.setEnabled(false);
                btnPesqCpfHospede.setEnabled(false);
                txtNumQuarto.setEnabled(true);
                btnPesqQuarto.setEnabled(true);
                txtNumQuarto.requestFocus();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Hópesde não cadastrado, favor realizar o cadastro ou pesquisar outro");
        }
    }//GEN-LAST:event_btnPesqCpfHospedeActionPerformed


    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        hotel.get(posQuarto).reservar((Hospede)cadastro.get(posHospede), (Atendente)cadastro.get(posAtendente));
        ((Atendente) cadastro.get(posAtendente)).addQuartoHotel(hotel.get(posQuarto));
        ((Hospede) cadastro.get(posHospede)).setQuartoHotel(hotel.get(posQuarto));
        
        hotel.get(posQuarto).setDataEntrada(txtDataEntrada.getText());
        
        txtRegFunc.setText(null);
        txtResultPesqFunc.setText(null);
        txtResultPesqHospede.setText(null);
        txtCpfHospede.setText(null);
        txtNumQuarto.setText(null);
        txtDataEntrada.setText(null);
        txtRegFunc.setEnabled(true);
        btnPesqRegFunc.setEnabled(true);
        txtCpfHospede.setEnabled(false);
        txtNumQuarto.setEnabled(false);
        btnPesqQuarto.setEnabled(false);
        txtDataEntrada.setEnabled(false);
        txtDataSaida.setEnabled(false);
        btnReservar.setEnabled(false);
        txtRegFunc.requestFocus();
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
            txtTotalPagar.setText(df.format(((Hospede) cadastro.get(posHospede)).getQuartoHotel()
                .liberar(calcularDias((((Hospede) cadastro.get(posHospede)).getQuartoHotel().getDataEntrada()),
                        txtDataSaida.getText()), ((Hospede) cadastro.get(posHospede)).getTxDesconto())));
            
            txtDataSaida.setEnabled(false);
            txtRegFunc.setEnabled(true);
            btnPesqRegFunc.setEnabled(true);
            txtRegFunc.requestFocus();
            
    }//GEN-LAST:event_btnLiberarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnPesqQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqQuartoActionPerformed
        int x;
        for (x = 0; x < hotel.size(); x++) {
            if (hotel.get(x) instanceof QuartoHotel) {
                if (hotel.get(x).getNumQuarto() == Integer.parseInt(txtNumQuarto.getText())) {
                    break;
                }
            }
        }
        
        if (x < hotel.size()) {
            posQuarto = x;
        } else {
            posQuarto = -1;
        }
        if (posQuarto >= 0) {
            if (hotel.get(posQuarto).isSituacao() == false) {
                txtSituacao.setText(" Livre");
                txtDataEntrada.setEnabled(true);
                txtDataEntrada.setText(null);
                txtDataSaida.setText(null);
                txtTotalPagar.setText(null);
                txtDataEntrada.requestFocus();
                btnReservar.setEnabled(true);
            } else {
                txtSituacao.setText(" Reservado");
                JOptionPane.showMessageDialog(this, "Quarto Reservado favor escolher outro quarto");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Quarto não cadastrado, favor realizar o cadastro ou pesquisar outro");
        }
    }//GEN-LAST:event_btnPesqQuartoActionPerformed
    
    private int calcularDias(String txtDt1, String txtDt2) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar data1 = Calendar.getInstance();
        Calendar data2 = Calendar.getInstance();
        int dias;
        try {
            data1.setTime(sdf.parse(txtDt1));
            data2.setTime(sdf.parse(txtDt2));
        } catch (java.text.ParseException e) {
        }
        dias = data2.get(Calendar.DAY_OF_YEAR) - data1.get(Calendar.DAY_OF_YEAR);
        return dias;
    }
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnPesqCpfHospede;
    private javax.swing.JButton btnPesqQuarto;
    private javax.swing.JButton btnPesqRegFunc;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField txtCpfHospede;
    private javax.swing.JTextField txtDataEntrada;
    private javax.swing.JTextField txtDataSaida;
    private javax.swing.JTextField txtNumQuarto;
    private javax.swing.JTextField txtRegFunc;
    private javax.swing.JTextField txtResultPesqFunc;
    private javax.swing.JTextField txtResultPesqHospede;
    private javax.swing.JTextField txtSituacao;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pessoa> cadastro = new ArrayList<Pessoa>();
    private ArrayList<QuartoHotel> hotel = new ArrayList<QuartoHotel>();
    private int posHospede;
    private int posAtendente;
    private int posQuarto;
    DecimalFormat df = new DecimalFormat("#,##0.00");
    
}
